import { Modules, ContainerRegistrationKeys } from '@medusajs/framework/utils'
import { INotificationModuleService, IOrderModuleService } from '@medusajs/framework/types'
import { SubscriberArgs, SubscriberConfig } from '@medusajs/medusa'
import { EmailTemplates } from '../modules/email-notifications/templates'
import { sendDashboardWebhook } from '../utils/webhook-signature'

export default async function orderPlacedHandler({
  event: { data },
  container,
}: SubscriberArgs<any>) {
  const notificationModuleService: INotificationModuleService = container.resolve(Modules.NOTIFICATION)
  const orderModuleService: IOrderModuleService = container.resolve(Modules.ORDER)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  
  // Use Query API to get complete order data with all calculated fields for items
  // retrieveOrder with relations doesn't include calculated totals like tax_total, subtotal, total
  const { data: ordersWithDetails } = await query.graph({
    entity: 'order',
    fields: [
      '*',
      'items.*',
      'items.tax_lines.*',
      'items.adjustments.*',
      'items.variant.*',
      'items.variant.product.*',
      'summary.*',
      'shipping_address.*',
      'billing_address.*',
      'customer.*',
    ],
    filters: { id: data.id },
  })
  
  const order = ordersWithDetails?.[0] as any
  if (!order) {
    console.error('❌ Could not fetch order details for order.placed webhook:', data.id)
    return
  }
  
  const shippingAddress = order.shipping_address
  
  // Get billing address - if not set, use shipping address as billing
  // Query API already returns full address data, no need for additional retrieval
  let billingAddress = order.billing_address
  if (!billingAddress && order.shipping_address) {
    billingAddress = order.shipping_address
  }

  // Get payment collections for this order
  let paymentCollections: any[] = []
  let capturedPayment: any = null
  
  try {
    const { data: ordersWithPayment } = await query.graph({
      entity: 'order',
      fields: [
        'id',
        'payment_collections.*',
        'payment_collections.payments.*',
      ],
      filters: { id: data.id },
    })
    
    const orderWithPayment = ordersWithPayment?.[0] as any
    paymentCollections = orderWithPayment?.payment_collections || []
    
    // Find captured payment
    const payments = paymentCollections[0]?.payments || []
    capturedPayment = payments.find((p: any) => p.captured_at !== null)
    
    if (capturedPayment) {
      console.log('💳 Found captured payment, including in order.placed webhook')
    }
  } catch (error) {
    console.error('⚠️  Could not fetch payment collections:', error)
  }

  // Send to Dashboard with payment data included
  // The dashboard will start the workflow if payment is captured
  console.log('📤 Sending order to Dashboard for invoice generation')
  console.log('📍 Billing address:', billingAddress ? `${billingAddress.first_name} ${billingAddress.last_name}, ${billingAddress.address_1}` : 'Not set')
  
  const result = await sendDashboardWebhook({
    endpoint: '/webhooks/medusa/orders',
    data: {
      ...order,
      // Explicitly include billing_address (falls back to shipping if not set)
      billing_address: billingAddress,
      payment_collections: paymentCollections,
      captured_payment: capturedPayment ? {
        id: capturedPayment.id,
        amount: capturedPayment.amount,
        currency_code: capturedPayment.currency_code,
        provider_id: capturedPayment.provider_id,
        captured_at: capturedPayment.captured_at,
        payment_collection_id: paymentCollections[0]?.id,
      } : null,
    },
    eventName: 'order.placed'
  })
  
  if (result.success) {
    console.log('✅ Order sent to Dashboard')
  } else {
    console.error('❌ Error sending order to Dashboard:', result.error)
  }

  // NOTE: Invoice PDF will be generated by Dashboard and synced back
  let pdfBuffer: Buffer | undefined
  let binaryString: string | undefined

  try {
    await notificationModuleService.createNotifications({
      to: order.email,
      channel: 'email',
      template: EmailTemplates.ORDER_PLACED,
      data: {
        emailOptions: {
          replyTo: 'info@matwi.se',
          subject: 'Your order has been placed'
        },
        order,
        shippingAddress,
        preview: 'Thank you for your order!'
      },
      ...(binaryString ? {
        attachments: [
          {
            content: binaryString,
            filename: `invoice-${order.id}.pdf`,
            content_type: "application/pdf",
            disposition: "attachment",
          },
        ],
      } : {}),
    })
  } catch (error) {
    console.error('Error sending order confirmation notification:', error)
  }
}

export const config: SubscriberConfig = {
  event: 'order.placed'
}
