import { Modules } from '@medusajs/framework/utils'
import { INotificationModuleService, IOrderModuleService } from '@medusajs/framework/types'
import { SubscriberArgs, SubscriberConfig } from '@medusajs/medusa'
import { EmailTemplates } from '../modules/email-notifications/templates'
import axios from 'axios'

export default async function orderPlacedHandler({
  event: { data },
  container,
}: SubscriberArgs<any>) {
  const notificationModuleService: INotificationModuleService = container.resolve(Modules.NOTIFICATION)
  const orderModuleService: IOrderModuleService = container.resolve(Modules.ORDER)
  
  const order = await orderModuleService.retrieveOrder(data.id, { relations: ['items', 'summary', 'shipping_address'] })
  const shippingAddress = await (orderModuleService as any).orderAddressService_.retrieve(order.shipping_address.id)

  // Send to Dashboard for invoice generation
  try {
    console.log('📤 Sending order to Dashboard for invoice generation')
    await axios.post(
      `${process.env.DASHBOARD_URL}/api/webhooks/medusa/orders`,
      order,
      {
        headers: {
          'X-Medusa-Event': 'order.placed',
          'Content-Type': 'application/json',
        }
      }
    )
    console.log('✅ Order sent to Dashboard')
  } catch (error) {
    console.error('❌ Error sending order to Dashboard:', error)
  }

  // NOTE: Invoice PDF will be generated by Dashboard and synced back
  let pdfBuffer: Buffer | undefined
  let binaryString: string | undefined

  try {
    await notificationModuleService.createNotifications({
      to: order.email,
      channel: 'email',
      template: EmailTemplates.ORDER_PLACED,
      data: {
        emailOptions: {
          replyTo: 'info@matwi.se',
          subject: 'Your order has been placed'
        },
        order,
        shippingAddress,
        preview: 'Thank you for your order!'
      },
      ...(binaryString ? {
        attachments: [
          {
            content: binaryString,
            filename: `invoice-${order.id}.pdf`,
            content_type: "application/pdf",
            disposition: "attachment",
          },
        ],
      } : {}),
    })
  } catch (error) {
    console.error('Error sending order confirmation notification:', error)
  }
}

export const config: SubscriberConfig = {
  event: 'order.placed'
}
